name: private_chat
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0'
dependencies:
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.13.6
  connectivity_plus: ^2.3.6
  country_picker: ^2.0.0
  country_pickers: ^2.0.0
  dio: ^5.4.0
  equatable: ^2.0.0
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_local_notifications: ^16.3.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  go_router: ^13.0.1
  pin_code_fields: ^7.3.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  sms_autofill: ^2.0.0
  timeago: ^3.6.0
  uuid: ^4.2.2
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
